#!/usr/bin/env bash
# Define the server's IP address or hostname

# Generate an RSA key pair with 4096 bits and passphrase "betty"
ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N "betty"

echo "RSA key pair created successfully."

